In [15]:
import numpy as np
x = np.matrix(np.arange(12).reshape((3,4)))
x
y = np.random.rand(3, 4)

In [24]:
for row in y:
    # print(row)
    ind = np.argpartition(row, -2)[-2:]
    print(ind)


[1 3]
[1 2]
[0 3]


In [16]:
z = np.argpartition(y, -2)[:, -2:]

In [68]:
z

array([[0, 2],
       [3, 2],
       [2, 0]])

In [80]:
ratings = np.zeros((3,4))
ratings[0, 2] = 1
ratings

array([[0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [90]:
np.take(ratings, z)

array([[0., 1.],
       [0., 1.],
       [1., 0.]])

In [105]:
b = list()

for i, row in enumerate(ratings):
    print(row)
    print(z[i])
    newrow = np.take(row, z[i])

    b.append(newrow)

b


[0. 0. 1. 0.]
[0 2]
[0. 0. 0. 0.]
[3 2]
[0. 0. 0. 0.]
[2 0]


[array([0., 1.]), array([0., 0.]), array([0., 0.])]

In [117]:
b = np.array(b)
b

array([[0., 1.],
       [0., 0.],
       [0., 0.]])

In [119]:
successful_picks = np.sum(b, axis=1)

In [131]:
np.where(ratings[0] > 0)

(array([2]),)

In [130]:
ratings[0]

array([0., 0., 1., 0.])

In [27]:
def get_recall(ratings, pred, m):
    ''' 
    inputs: 
        ratings matrix: [users, items]
        pred: floats [users, items]
        m: recall@M
    '''
    # generate number of items user likes among top M
    b = list()
    top_m = np.argpartition(pred, -m)[:, -m:]

    for i, row in enumerate(ratings):
        newrow = np.take(row, top_m[i])
        b.append(newrow)
    
    good_picks = np.sum(np.array(b), axis=1)

    # total number user likes
    user_picks = ratings.sum(axis=1)
    
    # generate recall
    user_recall = np.divide(good_picks, user_picks, where=user_picks!=0)
    return np.mean(user_recall)


In [170]:
pred = np.random.rand(3, 4)
ratings = np.array([0,0,0])

array([[1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
a.squeeze(axis=1).shape

(50, 10)

In [22]:
ratings = np.array([[0,0,0,1],[0,1,0,0],[0,0,1,1]])
ratings.shape

(3, 4)

In [32]:
pred = np.random.rand(3, 4)
pred

array([[0.92147057, 0.95363051, 0.40768573, 0.89857115],
       [0.33025325, 0.08273857, 0.52671757, 0.66084439],
       [0.89298429, 0.96515755, 0.76993268, 0.75909912]])

In [31]:
get_recall(ratings, pred, 1)

0.0